const infoList = {
  0: {
    id: 1,
    title: "Design: A Survival Guide for Beginners1",
    subtitle: "Posted 1 days ago",
    status: "Published",
    views: "120",
    viewsStatus: "up",
  },
  1: {
    id: 2,
    title: "Design: A Survival Guide for Beginners2",
    subtitle: "Posted 3 days ago",
    status: "Draft",
    views: "0",
    viewsStatus: "",
  },
  2: {
    id: 3,
    title: "Design: A Survival Guide for Beginners3",
    subtitle: "Posted 3 days ago",
    status: "Published",
    views: "80",
    viewsStatus: "down",
  },
  3: {
    id: 4,
    title: "Design: A Survival Guide for Beginners4",
    subtitle: "Posted 5 days ago",
    status: "Scheduled",
    views: "0",
    viewsStatus: "",
  },
  4: {
    id: 5,
    title: "Design: A Survival Guide for Beginners5",
    subtitle: "Posted 7 days ago",
    status: "Published",
    views: "35",
    viewsStatus: "up",
  },
  5: {
    id: 6,
    title: "Design: A Survival Guide for Beginners6",
    subtitle: "Posted 7 days ago",
    status: "Published",
    views: "35",
    viewsStatus: "up",
  },
  6: {
    id: 7,
    title: "Design: A Survival Guide for Beginners7",
    subtitle: "Posted 7 days ago",
    status: "Published",
    views: "35",
    viewsStatus: "up",
  },
  7: {
    id: 8,
    title: "Design: A Survival Guide for Beginners8",
    subtitle: "Posted 7 days ago",
    status: "Published",
    views: "35",
    viewsStatus: "up",
  },
  8: {
    id: 9,
    title: "Design: A Survival Guide for Beginners9",
    subtitle: "Posted 7 days ago",
    status: "Published",
    views: "35",
    viewsStatus: "up",
  },
  9: {
    id: 10,
    title: "Design: A Survival Guide for Beginners10",
    subtitle: "Posted 7 days ago",
    status: "Published",
    views: "35",
    viewsStatus: "up",
  },
};

export default infoList;
